language: node_js
node_js:
- '4'
sudo: false
dist: trusty
addons:
  chrome: stable
cache:
  directories:
  - "$HOME/.npm"
env:
  global:
  - JOBS=1
  matrix:
  - EMBER_TRY_SCENARIO=ember-1.13
  - EMBER_TRY_SCENARIO=ember-lts-2.12
  - EMBER_TRY_SCENARIO=ember-lts-2.16
  - EMBER_TRY_SCENARIO=ember-release
  - EMBER_TRY_SCENARIO=ember-beta
  - EMBER_TRY_SCENARIO=ember-canary
matrix:
  fast_finish: true
  allow_failures:
  - env: EMBER_TRY_SCENARIO=ember-canary
before_install:
- npm config set spin false
- npm install -g npm@4
- npm install -g bower
- npm --version
install:
- npm install
- bower install
script:
- npm run lint:js
- if [ "${EMBER_TRY_SCENARIO}" = "ember-release" ]; then ember try:one $EMBER_TRY_SCENARIO;
  else ember try:one $EMBER_TRY_SCENARIO --skip-cleanup; fi
deploy:
  provider: heroku
  api_key:
    secure: OeFMyi6ylYfPeNd/25cLaueVuVKbqtEHvis/J9GDiWIa7xpVD/NBS+TGxMTMaaA02Mft3Vw+MkZsPSWPU53ws1rQFAwAf98Pqx197dXoQ97Fi3wY0bipm9ZFl+bQYJg58Ydkz0sjQQbIxxtq9jn/gOtVTy5b+hQduSWjx3i15HE=
  app: ember-materialize-demo
  on:
    repo: mike-north/ember-cli-materialize
    condition: "$EMBER_TRY_SCENARIO = ember-release"
